os:
  - osx

language: go

install: true

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

script:
    - go get -v -u github.com/golang/dep/cmd/dep
    - dep ensure -v
    - go build ledger.go apduWrapper.go
    - go test
