[[constraint]]
  name = "github.com/zondax/ledger-go"
  version = "v0.7.0"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
      name = "github.com/zondax/hid"
      unused-packages = false
