[[constraint]]
  name = "github.com/ZondaX/ledger-go"
  version = "v0.5.0"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
      name = "github.com/karalabe/hid"
      unused-packages = false
