[[constraint]]
  name = "github.com/cosmos/ledger-go"
  version = "v0.9.1"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
      name = "github.com/zondax/hid"
      unused-packages = false
